Repository litmuschaos/chaos-operator, pull requests merged in 2019-10, with the labels that each got.

#65 (refactor): Refactor the chaosengine controller function
  pkg/controller/chaosengine/chaosengine_controller.go
  pkg/controller/chaosengine/types.go
Labels: BCH

#80 fix(UT): Add image field in unit test
  pkg/controller/chaosengine/chaosengine_controller_test.go
Labels: Unit Test, bug

#83 (feat): Add support for induce chaos of statefulset
  pkg/controller/resource/deployment.go
  pkg/controller/resource/resource.go
  pkg/controller/resource/statefulset.go
Labels: enhancement
